### ISSUE TITLE
IImportError: /mnt/Kodi_Backup/Applications/GenBrowser/venv/lib/python3.10/site-packages/PyQt5/QtWidgets.abi3.so: undefined symbol: _ZdlPvm, version Qt_5 

### ISSUE THREAD

**Issue by zono50** [imzacksong/GenBrowser#2]
when trying to start. What python version does this require? I created a python virtual environment, tried inside and outside of conda, and same issue. Doing this on arch linux.

**Comment by imzacksong** [comment]
i'm on python 3.12.4
